name: Push to Azure Blob Storage

on:
  push:
    branches:
      - main
    paths:
      - path/to/your/files/**

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/CLI@v1

    - name: Upload files to Azure Blob Storage
      env:
        AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
        AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
      run: |
        echo "Starting Azure Blob Storage upload..."
        az storage blob upload-batch \
          -d '/test/Azure_git_connect/' \
          --account-name $AZURE_STORAGE_ACCOUNT_NAME \
          --account-key $AZURE_STORAGE_ACCOUNT_KEY \
          -s path/to/your/files \
          || { echo "Azure CLI command failed"; exit 1; }
        echo "Azure Blob Storage upload completed."
